services:
  # poc:
  #   image: ${DOCKER_REGISTRY-}poc
  #   build:
  #     context: POC
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./volume/data:/data
  #   environment:
  #     - RADARR_URL=http://radarr:7878
  #     - RADARR_API_KEY=304cc33ba5024182ab5a2f408f843962

  sonarr: # tv
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
    volumes:
      - ./volume/sonarr-config:/config
      - ./volume/data:/data
    restart: unless-stopped
    depends_on:
      emulerr:
        condition: service_healthy

  radarr: # download movies
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
    volumes:
      - ./volume/radarr-config:/config
      - ./volume/data:/data
    restart: unless-stopped
    depends_on:
      emulerr:
        condition: service_healthy

  emulerr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMG_VER=2025-01-01-fffffff
    image: isc30/emulerr:latest
    container_name: emulerr
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3000 # optional, default=3000
      - ED2K_PORT=4762 # optional, default=4662
      - LOG_LEVEL=info # optional, default=info
      - PASSWORD=1234 # optional, user=emulerr
    ports:
      - "3000:3000" # web ui
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
      - "4711:4711" # DEV, amule webui
    volumes:
      - ./volume/config:/config
      - ./volume/data/usenet:/downloads
      
      # DEV MOUNTS, ignore
      - ./src:/emulerr-dev # DEV mount
      # - ./tmp:/emulerr-dev/node_modules # DEV mount
      - type: bind # DEV mount
        source: ./src/amule/api.php
        target: /usr/share/amule/webserver/AmuleWebUI-Reloaded/api.php
      - type: bind # DEV mount
        source: ./src/entrypoint.sh
        target: /home/entrypoint.sh
