/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV2TorrentsStopRouteImport } from './routes/api.v2.torrents.stop'
import { Route as ApiV2TorrentsStartRouteImport } from './routes/api.v2.torrents.start'
import { Route as ApiV2TorrentsSetCategoryRouteImport } from './routes/api.v2.torrents.setCategory'
import { Route as ApiV2TorrentsResumeRouteImport } from './routes/api.v2.torrents.resume'
import { Route as ApiV2TorrentsPauseRouteImport } from './routes/api.v2.torrents.pause'
import { Route as ApiV2TorrentsInfoRouteImport } from './routes/api.v2.torrents.info'
import { Route as ApiV2TorrentsFilesRouteImport } from './routes/api.v2.torrents.files'
import { Route as ApiV2TorrentsDeleteCategoryRouteImport } from './routes/api.v2.torrents.deleteCategory'
import { Route as ApiV2TorrentsDeleteRouteImport } from './routes/api.v2.torrents.delete'
import { Route as ApiV2TorrentsCreateCategoryRouteImport } from './routes/api.v2.torrents.createCategory'
import { Route as ApiV2TorrentsCategoriesRouteImport } from './routes/api.v2.torrents.categories'
import { Route as ApiV2TorrentsAddRouteImport } from './routes/api.v2.torrents.add'
import { Route as ApiV2SyncMaindataRouteImport } from './routes/api.v2.sync.maindata'
import { Route as ApiV2AuthLogoutRouteImport } from './routes/api.v2.auth.logout'
import { Route as ApiV2AuthLoginRouteImport } from './routes/api.v2.auth.login'
import { Route as ApiV2AppWebapiVersionRouteImport } from './routes/api.v2.app.webapiVersion'
import { Route as ApiV2AppVersionRouteImport } from './routes/api.v2.app.version'
import { Route as ApiV2AppPreferencesRouteImport } from './routes/api.v2.app.preferences'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2TorrentsStopRoute = ApiV2TorrentsStopRouteImport.update({
  id: '/v2/torrents/stop',
  path: '/v2/torrents/stop',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsStartRoute = ApiV2TorrentsStartRouteImport.update({
  id: '/v2/torrents/start',
  path: '/v2/torrents/start',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsSetCategoryRoute =
  ApiV2TorrentsSetCategoryRouteImport.update({
    id: '/v2/torrents/setCategory',
    path: '/v2/torrents/setCategory',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiV2TorrentsResumeRoute = ApiV2TorrentsResumeRouteImport.update({
  id: '/v2/torrents/resume',
  path: '/v2/torrents/resume',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsPauseRoute = ApiV2TorrentsPauseRouteImport.update({
  id: '/v2/torrents/pause',
  path: '/v2/torrents/pause',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsInfoRoute = ApiV2TorrentsInfoRouteImport.update({
  id: '/v2/torrents/info',
  path: '/v2/torrents/info',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsFilesRoute = ApiV2TorrentsFilesRouteImport.update({
  id: '/v2/torrents/files',
  path: '/v2/torrents/files',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsDeleteCategoryRoute =
  ApiV2TorrentsDeleteCategoryRouteImport.update({
    id: '/v2/torrents/deleteCategory',
    path: '/v2/torrents/deleteCategory',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiV2TorrentsDeleteRoute = ApiV2TorrentsDeleteRouteImport.update({
  id: '/v2/torrents/delete',
  path: '/v2/torrents/delete',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsCreateCategoryRoute =
  ApiV2TorrentsCreateCategoryRouteImport.update({
    id: '/v2/torrents/createCategory',
    path: '/v2/torrents/createCategory',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiV2TorrentsCategoriesRoute = ApiV2TorrentsCategoriesRouteImport.update({
  id: '/v2/torrents/categories',
  path: '/v2/torrents/categories',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2TorrentsAddRoute = ApiV2TorrentsAddRouteImport.update({
  id: '/v2/torrents/add',
  path: '/v2/torrents/add',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2SyncMaindataRoute = ApiV2SyncMaindataRouteImport.update({
  id: '/v2/sync/maindata',
  path: '/v2/sync/maindata',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2AuthLogoutRoute = ApiV2AuthLogoutRouteImport.update({
  id: '/v2/auth/logout',
  path: '/v2/auth/logout',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2AuthLoginRoute = ApiV2AuthLoginRouteImport.update({
  id: '/v2/auth/login',
  path: '/v2/auth/login',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2AppWebapiVersionRoute = ApiV2AppWebapiVersionRouteImport.update({
  id: '/v2/app/webapiVersion',
  path: '/v2/app/webapiVersion',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2AppVersionRoute = ApiV2AppVersionRouteImport.update({
  id: '/v2/app/version',
  path: '/v2/app/version',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV2AppPreferencesRoute = ApiV2AppPreferencesRouteImport.update({
  id: '/v2/app/preferences',
  path: '/v2/app/preferences',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/health': typeof HealthRoute
  '/api/v2/app/preferences': typeof ApiV2AppPreferencesRoute
  '/api/v2/app/version': typeof ApiV2AppVersionRoute
  '/api/v2/app/webapiVersion': typeof ApiV2AppWebapiVersionRoute
  '/api/v2/auth/login': typeof ApiV2AuthLoginRoute
  '/api/v2/auth/logout': typeof ApiV2AuthLogoutRoute
  '/api/v2/sync/maindata': typeof ApiV2SyncMaindataRoute
  '/api/v2/torrents/add': typeof ApiV2TorrentsAddRoute
  '/api/v2/torrents/categories': typeof ApiV2TorrentsCategoriesRoute
  '/api/v2/torrents/createCategory': typeof ApiV2TorrentsCreateCategoryRoute
  '/api/v2/torrents/delete': typeof ApiV2TorrentsDeleteRoute
  '/api/v2/torrents/deleteCategory': typeof ApiV2TorrentsDeleteCategoryRoute
  '/api/v2/torrents/files': typeof ApiV2TorrentsFilesRoute
  '/api/v2/torrents/info': typeof ApiV2TorrentsInfoRoute
  '/api/v2/torrents/pause': typeof ApiV2TorrentsPauseRoute
  '/api/v2/torrents/resume': typeof ApiV2TorrentsResumeRoute
  '/api/v2/torrents/setCategory': typeof ApiV2TorrentsSetCategoryRoute
  '/api/v2/torrents/start': typeof ApiV2TorrentsStartRoute
  '/api/v2/torrents/stop': typeof ApiV2TorrentsStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/health': typeof HealthRoute
  '/api/v2/app/preferences': typeof ApiV2AppPreferencesRoute
  '/api/v2/app/version': typeof ApiV2AppVersionRoute
  '/api/v2/app/webapiVersion': typeof ApiV2AppWebapiVersionRoute
  '/api/v2/auth/login': typeof ApiV2AuthLoginRoute
  '/api/v2/auth/logout': typeof ApiV2AuthLogoutRoute
  '/api/v2/sync/maindata': typeof ApiV2SyncMaindataRoute
  '/api/v2/torrents/add': typeof ApiV2TorrentsAddRoute
  '/api/v2/torrents/categories': typeof ApiV2TorrentsCategoriesRoute
  '/api/v2/torrents/createCategory': typeof ApiV2TorrentsCreateCategoryRoute
  '/api/v2/torrents/delete': typeof ApiV2TorrentsDeleteRoute
  '/api/v2/torrents/deleteCategory': typeof ApiV2TorrentsDeleteCategoryRoute
  '/api/v2/torrents/files': typeof ApiV2TorrentsFilesRoute
  '/api/v2/torrents/info': typeof ApiV2TorrentsInfoRoute
  '/api/v2/torrents/pause': typeof ApiV2TorrentsPauseRoute
  '/api/v2/torrents/resume': typeof ApiV2TorrentsResumeRoute
  '/api/v2/torrents/setCategory': typeof ApiV2TorrentsSetCategoryRoute
  '/api/v2/torrents/start': typeof ApiV2TorrentsStartRoute
  '/api/v2/torrents/stop': typeof ApiV2TorrentsStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/health': typeof HealthRoute
  '/api/v2/app/preferences': typeof ApiV2AppPreferencesRoute
  '/api/v2/app/version': typeof ApiV2AppVersionRoute
  '/api/v2/app/webapiVersion': typeof ApiV2AppWebapiVersionRoute
  '/api/v2/auth/login': typeof ApiV2AuthLoginRoute
  '/api/v2/auth/logout': typeof ApiV2AuthLogoutRoute
  '/api/v2/sync/maindata': typeof ApiV2SyncMaindataRoute
  '/api/v2/torrents/add': typeof ApiV2TorrentsAddRoute
  '/api/v2/torrents/categories': typeof ApiV2TorrentsCategoriesRoute
  '/api/v2/torrents/createCategory': typeof ApiV2TorrentsCreateCategoryRoute
  '/api/v2/torrents/delete': typeof ApiV2TorrentsDeleteRoute
  '/api/v2/torrents/deleteCategory': typeof ApiV2TorrentsDeleteCategoryRoute
  '/api/v2/torrents/files': typeof ApiV2TorrentsFilesRoute
  '/api/v2/torrents/info': typeof ApiV2TorrentsInfoRoute
  '/api/v2/torrents/pause': typeof ApiV2TorrentsPauseRoute
  '/api/v2/torrents/resume': typeof ApiV2TorrentsResumeRoute
  '/api/v2/torrents/setCategory': typeof ApiV2TorrentsSetCategoryRoute
  '/api/v2/torrents/start': typeof ApiV2TorrentsStartRoute
  '/api/v2/torrents/stop': typeof ApiV2TorrentsStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/health'
    | '/api/v2/app/preferences'
    | '/api/v2/app/version'
    | '/api/v2/app/webapiVersion'
    | '/api/v2/auth/login'
    | '/api/v2/auth/logout'
    | '/api/v2/sync/maindata'
    | '/api/v2/torrents/add'
    | '/api/v2/torrents/categories'
    | '/api/v2/torrents/createCategory'
    | '/api/v2/torrents/delete'
    | '/api/v2/torrents/deleteCategory'
    | '/api/v2/torrents/files'
    | '/api/v2/torrents/info'
    | '/api/v2/torrents/pause'
    | '/api/v2/torrents/resume'
    | '/api/v2/torrents/setCategory'
    | '/api/v2/torrents/start'
    | '/api/v2/torrents/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/health'
    | '/api/v2/app/preferences'
    | '/api/v2/app/version'
    | '/api/v2/app/webapiVersion'
    | '/api/v2/auth/login'
    | '/api/v2/auth/logout'
    | '/api/v2/sync/maindata'
    | '/api/v2/torrents/add'
    | '/api/v2/torrents/categories'
    | '/api/v2/torrents/createCategory'
    | '/api/v2/torrents/delete'
    | '/api/v2/torrents/deleteCategory'
    | '/api/v2/torrents/files'
    | '/api/v2/torrents/info'
    | '/api/v2/torrents/pause'
    | '/api/v2/torrents/resume'
    | '/api/v2/torrents/setCategory'
    | '/api/v2/torrents/start'
    | '/api/v2/torrents/stop'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/health'
    | '/api/v2/app/preferences'
    | '/api/v2/app/version'
    | '/api/v2/app/webapiVersion'
    | '/api/v2/auth/login'
    | '/api/v2/auth/logout'
    | '/api/v2/sync/maindata'
    | '/api/v2/torrents/add'
    | '/api/v2/torrents/categories'
    | '/api/v2/torrents/createCategory'
    | '/api/v2/torrents/delete'
    | '/api/v2/torrents/deleteCategory'
    | '/api/v2/torrents/files'
    | '/api/v2/torrents/info'
    | '/api/v2/torrents/pause'
    | '/api/v2/torrents/resume'
    | '/api/v2/torrents/setCategory'
    | '/api/v2/torrents/start'
    | '/api/v2/torrents/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/torrents/stop': {
      id: '/api/v2/torrents/stop'
      path: '/v2/torrents/stop'
      fullPath: '/api/v2/torrents/stop'
      preLoaderRoute: typeof ApiV2TorrentsStopRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/start': {
      id: '/api/v2/torrents/start'
      path: '/v2/torrents/start'
      fullPath: '/api/v2/torrents/start'
      preLoaderRoute: typeof ApiV2TorrentsStartRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/setCategory': {
      id: '/api/v2/torrents/setCategory'
      path: '/v2/torrents/setCategory'
      fullPath: '/api/v2/torrents/setCategory'
      preLoaderRoute: typeof ApiV2TorrentsSetCategoryRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/resume': {
      id: '/api/v2/torrents/resume'
      path: '/v2/torrents/resume'
      fullPath: '/api/v2/torrents/resume'
      preLoaderRoute: typeof ApiV2TorrentsResumeRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/pause': {
      id: '/api/v2/torrents/pause'
      path: '/v2/torrents/pause'
      fullPath: '/api/v2/torrents/pause'
      preLoaderRoute: typeof ApiV2TorrentsPauseRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/info': {
      id: '/api/v2/torrents/info'
      path: '/v2/torrents/info'
      fullPath: '/api/v2/torrents/info'
      preLoaderRoute: typeof ApiV2TorrentsInfoRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/files': {
      id: '/api/v2/torrents/files'
      path: '/v2/torrents/files'
      fullPath: '/api/v2/torrents/files'
      preLoaderRoute: typeof ApiV2TorrentsFilesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/deleteCategory': {
      id: '/api/v2/torrents/deleteCategory'
      path: '/v2/torrents/deleteCategory'
      fullPath: '/api/v2/torrents/deleteCategory'
      preLoaderRoute: typeof ApiV2TorrentsDeleteCategoryRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/delete': {
      id: '/api/v2/torrents/delete'
      path: '/v2/torrents/delete'
      fullPath: '/api/v2/torrents/delete'
      preLoaderRoute: typeof ApiV2TorrentsDeleteRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/createCategory': {
      id: '/api/v2/torrents/createCategory'
      path: '/v2/torrents/createCategory'
      fullPath: '/api/v2/torrents/createCategory'
      preLoaderRoute: typeof ApiV2TorrentsCreateCategoryRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/categories': {
      id: '/api/v2/torrents/categories'
      path: '/v2/torrents/categories'
      fullPath: '/api/v2/torrents/categories'
      preLoaderRoute: typeof ApiV2TorrentsCategoriesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/torrents/add': {
      id: '/api/v2/torrents/add'
      path: '/v2/torrents/add'
      fullPath: '/api/v2/torrents/add'
      preLoaderRoute: typeof ApiV2TorrentsAddRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/sync/maindata': {
      id: '/api/v2/sync/maindata'
      path: '/v2/sync/maindata'
      fullPath: '/api/v2/sync/maindata'
      preLoaderRoute: typeof ApiV2SyncMaindataRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/auth/logout': {
      id: '/api/v2/auth/logout'
      path: '/v2/auth/logout'
      fullPath: '/api/v2/auth/logout'
      preLoaderRoute: typeof ApiV2AuthLogoutRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/auth/login': {
      id: '/api/v2/auth/login'
      path: '/v2/auth/login'
      fullPath: '/api/v2/auth/login'
      preLoaderRoute: typeof ApiV2AuthLoginRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/app/webapiVersion': {
      id: '/api/v2/app/webapiVersion'
      path: '/v2/app/webapiVersion'
      fullPath: '/api/v2/app/webapiVersion'
      preLoaderRoute: typeof ApiV2AppWebapiVersionRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/app/version': {
      id: '/api/v2/app/version'
      path: '/v2/app/version'
      fullPath: '/api/v2/app/version'
      preLoaderRoute: typeof ApiV2AppVersionRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v2/app/preferences': {
      id: '/api/v2/app/preferences'
      path: '/v2/app/preferences'
      fullPath: '/api/v2/app/preferences'
      preLoaderRoute: typeof ApiV2AppPreferencesRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiV2AppPreferencesRoute: typeof ApiV2AppPreferencesRoute
  ApiV2AppVersionRoute: typeof ApiV2AppVersionRoute
  ApiV2AppWebapiVersionRoute: typeof ApiV2AppWebapiVersionRoute
  ApiV2AuthLoginRoute: typeof ApiV2AuthLoginRoute
  ApiV2AuthLogoutRoute: typeof ApiV2AuthLogoutRoute
  ApiV2SyncMaindataRoute: typeof ApiV2SyncMaindataRoute
  ApiV2TorrentsAddRoute: typeof ApiV2TorrentsAddRoute
  ApiV2TorrentsCategoriesRoute: typeof ApiV2TorrentsCategoriesRoute
  ApiV2TorrentsCreateCategoryRoute: typeof ApiV2TorrentsCreateCategoryRoute
  ApiV2TorrentsDeleteRoute: typeof ApiV2TorrentsDeleteRoute
  ApiV2TorrentsDeleteCategoryRoute: typeof ApiV2TorrentsDeleteCategoryRoute
  ApiV2TorrentsFilesRoute: typeof ApiV2TorrentsFilesRoute
  ApiV2TorrentsInfoRoute: typeof ApiV2TorrentsInfoRoute
  ApiV2TorrentsPauseRoute: typeof ApiV2TorrentsPauseRoute
  ApiV2TorrentsResumeRoute: typeof ApiV2TorrentsResumeRoute
  ApiV2TorrentsSetCategoryRoute: typeof ApiV2TorrentsSetCategoryRoute
  ApiV2TorrentsStartRoute: typeof ApiV2TorrentsStartRoute
  ApiV2TorrentsStopRoute: typeof ApiV2TorrentsStopRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiV2AppPreferencesRoute: ApiV2AppPreferencesRoute,
  ApiV2AppVersionRoute: ApiV2AppVersionRoute,
  ApiV2AppWebapiVersionRoute: ApiV2AppWebapiVersionRoute,
  ApiV2AuthLoginRoute: ApiV2AuthLoginRoute,
  ApiV2AuthLogoutRoute: ApiV2AuthLogoutRoute,
  ApiV2SyncMaindataRoute: ApiV2SyncMaindataRoute,
  ApiV2TorrentsAddRoute: ApiV2TorrentsAddRoute,
  ApiV2TorrentsCategoriesRoute: ApiV2TorrentsCategoriesRoute,
  ApiV2TorrentsCreateCategoryRoute: ApiV2TorrentsCreateCategoryRoute,
  ApiV2TorrentsDeleteRoute: ApiV2TorrentsDeleteRoute,
  ApiV2TorrentsDeleteCategoryRoute: ApiV2TorrentsDeleteCategoryRoute,
  ApiV2TorrentsFilesRoute: ApiV2TorrentsFilesRoute,
  ApiV2TorrentsInfoRoute: ApiV2TorrentsInfoRoute,
  ApiV2TorrentsPauseRoute: ApiV2TorrentsPauseRoute,
  ApiV2TorrentsResumeRoute: ApiV2TorrentsResumeRoute,
  ApiV2TorrentsSetCategoryRoute: ApiV2TorrentsSetCategoryRoute,
  ApiV2TorrentsStartRoute: ApiV2TorrentsStartRoute,
  ApiV2TorrentsStopRoute: ApiV2TorrentsStopRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
